### ISSUE TITLE
Stats of the memory optimised 

### ISSUE THREAD

**Issue by SarthakJain26** [dkorunic/betteralign#12]
Understanding the metrics is crucial, especially when there is a noticeable enhancement. This request is for the inclusion of a feature that would add details regarding the percentage or quantity of memory optimized after the execution of the `betteralign ./...` command. Such information would contribute to a more comprehensive assessment of the impact and effectiveness of the optimization process.

**Comment by dkorunic** [comment]
Partially addressed in https://github.com/dkorunic/betteralign/pull/13.

**Comment by dkorunic** [comment]
I think we can close this for now.
