### ISSUE TITLE
BetterAlign can't detect struct without named fields

### ISSUE THREAD

**Issue by gaby** [dkorunic/betteralign#15]
When structs are used without specifying fields, `betteralign` breaks the code.

```go
type geo struct {
  x int
  y int
}

g := geo{5, 6}
```

Let's assume that `betteralign` changed the struct order to `Y, X`. The code will now store 5 for Y instead of X.

@dkorunic Any idea around this? I'm not sure if it's a `betteralign` issue, or if it should be cover by some other tool. I can't find any that enforces initialization with names.

**Comment by dkorunic** [comment]
Hi @gaby, that's sadly a [known issue](https://github.com/dkorunic/betteralign/issues/3) and there is no workaround yet, but you can mark the struct with `//betteralign:ignore` and betteralign will ignore it when sorting.

**Comment by gaby** [comment]
@dkorunic I ended up writing my own analyzer to convert positional fields to named fields. After doing that I can safely run `betteralign`.

I plan on publishing it, will report back here.

**Comment by dkorunic** [comment]
@gaby I'll gladly put a link to it in the README, if you don't mind.

**Comment by dkorunic** [comment]
Should be resolved in https://github.com/dkorunic/betteralign/releases/tag/v0.5.0.

**Comment by gaby** [comment]
@dkorunic Thanks! That's awesome
