### ISSUE TITLE
Add support for an exclude-dirs/ignore config

### ISSUE THREAD

**Issue by adrienlucbert** [dkorunic/betteralign#16]
`golangci` has a config option to ignore certain paths/dirs: https://golangci-lint.run/usage/configuration/#issues-configuration
I think it would be super useful to have a similar option, I'm down to write a pull request for that, I just wanted to ask for your take on this @dkorunic.

If I were to implement this, would you rather like it to be:
- a dedicated config file
- a CLI option
- relying on a more generic/already existing config (`.golangci.yml` or similar)

Thanks for your time :pray:

**Comment by dkorunic** [comment]
Hi @adrienlucbert, given how `analysis.Analyzer` works, I think it's by far the most logical to add a CLI flag for this. Path-wise, current filename being inspected is in:
```
                fn := pass.Fset.File(node.Pos()).Name()
```

**Comment by adrienlucbert** [comment]
As I'm pursuing my research, I found that `singlechecker` that you use uses `unitchecker` under the hood, which already seems to support ignoring files via a config `.cfg` file: https://github.com/golang/tools/blob/master/go/analysis/unitchecker/unitchecker.go#L56
`betteralign .betteralign.cfg` attempts parsing the config file `.betteralign.cfg` to populate the compilation unit to be processed.

**Comment by adrienlucbert** [comment]
Nevermind that doesn't seem to be appropriate, I found a not-so-robust workaround for my situation but I'll see to start working on the PR tonight.
Thanks again!
