### ISSUE TITLE
Tool crashes when encountering empty directories in search path

### ISSUE THREAD

**Issue by Coronon** [dkorunic/betteralign#18]
First of all, thank you for this awesome tool! I've been using it extensively across many of my projects, and it has been incredibly helpful. However, I've encountered a recurring issue that impacts every project I work on.

The tool crashes with the following error message if it encounters an empty directory in its search path: `betteralign: analysis skipped due to errors in package`. This behavior makes it challenging to work with project structures that include empty directories.

I typically run the tool using the following command: `betteralign -apply ./internal/***`. Here, `internal/` contains multiple subdirectories representing packages. However, for organizational reasons, there are cases where directories inside `internal/` are not themselves packages but instead serve as containers for additional packages. For example:

```
.
└── internal/
    ├── a/
    │   └── a.go
    ├── b/
    │   └── b.go
    └── problematic_folder/
        ├── c/
        │   └── c.go
        ├── d/
        │   └── d.go
        └── placeholder.go     <--------------- WILL CRASH WITHOUT THIS FILE
```

Could this behavior be addressed in a future update? It would significantly improve usability, especially for larger projects where empty directories are inevitable during development.

**Comment by dkorunic** [comment]
I'll check this right away. Also thank you for kind words @Coronon!

**Comment by dkorunic** [comment]
@Coronon I have tried to reproduce this with various combinations of the above and in real life projects and I have failed to do so. Please, send me a log with the crash that shows the behaviour of betteralign when used on a such project. Tool should be run as follows: `betteralign './...'`. Thank you in advance!

**Comment by Coronon** [comment]
Thank you very much for your quick response!

It turns out the issue was indeed caused by my invocation using `./internal/***`. This pattern expands to all subdirectories, including any empty ones. Switching to `./internal/...` resolved the issue for me, as I wasn’t aware of this specific Go package discovery syntax.

That said, it might still be beneficial to handle this scenario more gracefully. Perhaps a warning for empty directories instead of a failure would be helpful. For reference, the error I encountered was:
```
-: no Go files in /my_full_path/internal/empty_dir
[100+ lines of '{PATH} 56 bytes saved: struct with 232 pointer bytes could be 176']
betteralign: analysis skipped due to errors in package
```

This error message made diagnosing the root cause rather challenging, especially due to the volume of unrelated output. A more targeted warning might improve the debugging experience.

Here is a simple reproduction: https://github.com/Coronon/betteralign-reproduction

**Comment by dkorunic** [comment]
Right, Go syntax for traversing all sources and packages is `./...` typically. In regards to shown errors, they are propagating from lower-level Go internal packages (`load` and `lsp/cache`) and singlechecker runs are showing individual analysis errors. There is nothing here to fix, at least not in betteralign -- I am merely reusing existing Golang analysis/singlechecker framework.
