### ISSUE TITLE
go install fails

### ISSUE THREAD

**Issue by cemremengu** [dkorunic/betteralign#2]
I am on windows running the command and getting the following error:

```
go install github.com/dkorunic/betteralign/cmd/betteralign@latest
# github.com/dkorunic/betteralign
..\..\go\pkg\mod\github.com\dkorunic\betteralign@v0.2.2\betteralign.go:519:21: undefined: renameio.WriteFile
..\..\go\pkg\mod\github.com\dkorunic\betteralign@v0.2.2\betteralign.go:519:60: undefined: renameio.IgnoreUmask
```

**Comment by dkorunic** [comment]
Sadly @cemremengu that's expected -- renameio library doesn't support Windows platform due to lack of atomic I/O. I can possibly add a dummy function that will write and rename files emulating atomic I/O, but there will be no guarantees like on Un*x and Linux systems.
