### ISSUE TITLE
Incorrect size calculation?

### ISSUE THREAD

**Issue by derlaft** [dkorunic/betteralign#7]
Given the code:

```
type structB struct {
	b uint8
	a net.IP
}
```

`betteralign` suggests to realign:

```
% betteralign ./...
/tmp/tmp.RrY2d8UsZv/main.go:14:14: struct with 16 pointer bytes could be 8
```

[However, that makes no difference](https://go.dev/play/p/2zkAvf6HXRs):

```
size of *main.structA = 32
size of *main.structB = 32
```

**Comment by dkorunic** [comment]
@derlaft Report states the amount of object bytes that GC has to scan for pointers. With the following:

```
type structB struct {
        a net.IP
        b uint8
}
```

GC would scan first 8 bytes for pointers (net.IP type) and immediately stop upon reaching uint8 type.

**Comment by derlaft** [comment]
Thanks a lot!

**Comment by derlaft** [comment]
btw is there an article (or anything similar) that I could read about that effect on GC? would be interesting to know more details, but so far cannot find anything

**Comment by derlaft** [comment]
nvm, found it :) https://cs.opensource.google/go/x/tools/+/refs/tags/v0.9.1:go/analysis/passes/fieldalignment/fieldalignment.go;l=23
