### ISSUE TITLE
convert app to use as package

### ISSUE THREAD

**Issue by vtolstov** [dkorunic/betteralign#8]
i'm very interesting to reuse you code to align my files after it generated, do you plan to change code to be able to use as package?

**Comment by dkorunic** [comment]
Dear @vtolstov I'm not sure what you mean with the `package` term. Since betteralign is already `singlechecker` Analyzer which you can import with `import github.com/dkorunic/betteralign` if you wish so, I'm not really sure what are you requesting here. Can you explain please?

**Comment by vtolstov** [comment]
yeah thanks!
